server:
  port: 8081

spring:
  profiles:
    active: config1
  application:
    name: sc-gateway-service

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

---
spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lowerCaseServiceId: true
  profiles: config1

---
spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: false
          lowerCaseServiceId: true
      routes:
        - id: service-hi
          uri: lb://SERVICE-HI
          predicates:
            - Path=/demo/**
          filters:
            - StripPrefix=1
  profiles: config2